### ISSUE TITLE
Hide indicator

### ISSUE THREAD

**Issue by adi90x** [artem-sedykh/mini-climate-card#114]
Hello,

Thanks a lot for this very nice card, one quick question is it possible to hide some indicator (using a mapping fonction ?)

In my use case, I want to display a specific indicator only when an attribute of the climate entity is true.

It seems that hide key is working ( i.e ``hide : true``  works) but templating don't seems to be handled.
Is it something not available at the moment or am I doing it wrong ?

Regards,
Adrien

**Comment by adi90x** [comment]
Will have a look tonight and push something

**Comment by regevbr** [comment]
done in #118 and released in 2.5.0.

**Comment by adi90x** [comment]
Works great !
