### ISSUE TITLE
v2.5.0 broke for me

### ISSUE THREAD

**Issue by TomaszDom** [artem-sedykh/mini-climate-card#119]
I have had the same configuration for months, after updating to v2.5.0 it broke for me.

![Screenshot_20230409_111139_Home Assistant](https://user-images.githubusercontent.com/9348532/230764755-7c73d6f4-170e-41c6-b5b1-662060480201.jpg)

This is my configuration (one of many which broke but they just differ by entity)

`type: custom:mini-climate
entity: climate.lazienka_grzejnik
target_temperature:
  step: 0.5
secondary_info: hvac-mode
indicators:
  valve:
    icon: mdi:valve
    unit: '%'
    round: 1
    source:
      entity: sensor.lazienka_grzejnik_position
  preset_mode:
    icon: mdi:car-cruise-control
    source:
      attribute: preset_mode
icon: mdi:radiator
fan_mode:
  hide: 'on'
  active: false
  icon: mdi:none
  disabled: true
buttons:
  preset_mode:
    type: dropdown
    location: main
    icon: mdi:thermometer
    state:
      attribute: preset_mode
    active: state => state !== 'none'
    source:
      eco: Eco
      comfort: Comfort
      boost: Boost
      manual: Manual
    change_action: >
      (selected, state, entity) => this.call_service('climate',
      'set_preset_mode', { entity_id: entity.entity_id, preset_mode: selected })
`

**Comment by regevbr** [comment]
Hide should be a boolean

**Comment by TomaszDom** [comment]
I changed it and now it's working again. Thanks. I've had this config for a very long time without any changes so something changed in the code that broke it.
