### ISSUE TITLE
Dropdown not working in android app

### ISSUE THREAD

**Issue by hopperjef** [artem-sedykh/mini-climate-card#124]
In the android app the dropdown menu for "secondary_info" and "hvac_mode (I think)" doesn't seem to be working in certain instances. I have 5 cards running mini-climate and for 3 of them the dropdown works just fine but for two of them the dropdown does not appear at all. 
![Screenshot_20230523_152404_Home Assistant](https://github.com/artem-sedykh/mini-climate-card/assets/79919919/0863c2ea-2107-44a5-890c-baa9b829ebce)

**Comment by gador** [comment]
I have the same issue. 
climate: v2.6.1
HACS: Integrations Version: | 1.32.1
HACS Frontend Version: | 20220906112053
Home Assistant 2023.5.4

**Comment by regevbr** [comment]
If someone can try to fix it and submit a PR, I will review and release it promptly. Sadly, CSS is out of my scope of expertise

**Comment by regevbr** [comment]
Released in 2.6.2

**Comment by itssimon** [comment]
Unfortunately this fix did not fix it for iOS where the dropdown also doesn't work.

**Comment by regevbr** [comment]
If you just installed it, it takes forever for the mobile apps to refresh itself, give it a couple of days please and report back. 
The issue was not just android related and I reproduced it on my PC browser, that is why I don't think it exists just for IOS
