### ISSUE TITLE
Change color of main icon 

### ISSUE THREAD

**Issue by razsteinmetz** [artem-sedykh/mini-climate-card#135]
Hi,
Maybe you can give an example how to change the color of the default mdi:air-conditioner?  I was able to change all other icons colors with the style entry, but how do you change the main icon color?
many thanks

**Comment by regevbr** [comment]
Currently, you can't from code. You can hard code it using CSS variables in the [theme](https://community.home-assistant.io/t/can-we-change-add-variables-to-default-theme/214507)

off: --mini-climate-icon-color/--mini-climate-base-color
on: --state-binary_sensor-active-color

A PR is more than welcome to add that ability if you desire
