### ISSUE TITLE
Card doesnt load using latest (or Beta) version of Chrome

### ISSUE THREAD

**Issue by minigranis** [artem-sedykh/mini-climate-card#139]
Hello.
When using Chrome version Version 120.0.6099.200 (Official Build) (64-bit) or Chrome Beta Version 121.0.6167.47 (Official Build) beta (64-bit) the Mini-Climate card doesnt "load", it simply doesnt show up in Lovelace. All my other cards work and if I use Edge mini climate works as it should. 
The same config used to work in Chrome as well but stopped a few Chrome updates ago but then the Beta of Chrome worked but now after a Beta update it doesnt load on the Beta either. 

Can you look into this please.
Here is a part of my yaml code:
      - type: custom:mini-climate
        entity: climate.vardagsrum_srt321_3
        icon: mdi:heat-wave
        toggle:
          hide: true
        secondary_info: hvac-mode
        target_temperature:
          min: 5
        hvac_mode:
          hide: true
        indicators:
          power1:
            icon:
              template: () => 'mdi:power-plug'
              style: |
                (value) => (value == "on" ? { color: 'orange'} : {})
            source:
              entity: switch.vardagsrum_soffan_aeon_mss2
          power2:
            icon:
              template: () => 'mdi:power-plug'
              style: |
                (value) => (value == "on" ? { color: 'orange'} : {})
            source:
              entity: switch.element_kok_shelly_1_pm

**Comment by regevbr** [comment]
https://github.com/artem-sedykh/mini-climate-card/issues/137
You need to disable the chrome://flags/#enable-experimental-web-platform-features flag to fix it

**Comment by minigranis** [comment]
Arghh - simple as that - Thanks for a quick response.
