### ISSUE TITLE
I Cannot Get This to Work to Save My Life

### ISSUE THREAD

**Issue by RyanWoirol** [artem-sedykh/mini-climate-card#22]
I'm not the smartest when it comes to HA, but have been able to do decent so far.  

I am not a fan of the standard Thermostat card, and Simple works fine but this one looks great.  

When I try to get it set in lovelace, it gives me the red "No Card Type Configured".  I can't figure it out, please help.

**Comment by maparker** [comment]
@RyanWoirol Not sure if you have resolved this or not. I had the same problem. I fixed mine by removing the '- ' at the beginning of 'type:' and then making sure the indentation was correct. Mine now looks like this:
`type: 'custom:mini-climate'
entity: climate.home
hvac_mode:
  style: '(value, entity) => ({ color: ''black'' })'
  source:
    'off':
      icon: 'mdi:power'
      name: 'off'
    heat:
      icon: 'mdi:weather-sunny'
      name: heat
    auto:
      icon: 'mdi:cached'
      name: auto
    cool:
      icon: 'mdi:snowflake'
      name: cool
    dry:
      icon: 'mdi:water'
      name: dry
    fan_only:
      icon: 'mdi:fan'
      name: fan
  change_action: >
    (selected, entity) => this.call_service('climate', 'set_hvac_mode', {
    entity_id: entity.entity_id, hvac_mode: selected })
openssl s_client -state -connect graph.facebook.com:443`

**Comment by RyanWoirol** [comment]
You are a lifesaver.  Thank you, I was starting to really pull out my already thinning hair.
