### ISSUE TITLE
Secondary-info and indicators not center when toogle is hidden

### ISSUE THREAD

**Issue by tibortiz** [artem-sedykh/mini-climate-card#23]
When i'm hidding the toogle menu with : 
```
toggle:
  hide: true
```

The first card don't have the toogle hidden when the second one have:
![image](https://user-images.githubusercontent.com/25587210/84524064-a1c2cb80-acd9-11ea-91b1-3d5c5d83b30f.png)

Maybe we can center a bit more the secondary info and the indicators value, in that specific case

**Comment by artem-sedykh** [comment]
So fit?  
![image](https://user-images.githubusercontent.com/861063/84592022-3bf65100-ae4b-11ea-96b3-53159a441fe4.png)

**Comment by tibortiz** [comment]
@artem-sedykh It will be perfect !

**Comment by artem-sedykh** [comment]
fixed in [v1.2.4](https://github.com/artem-sedykh/mini-climate-card/releases/tag/v1.2.4)
