### ISSUE TITLE
Uninstall issue

### ISSUE THREAD

**Issue by tborychowski** [artem-sedykh/mini-climate-card#25]
After I to uninstall it, the logs show this:
```
Tried to serve up '/config/www/community/mini-climate-card/mini-climate-card-bundle.js' but it does not exist
```
The folder is gone, but the entry must sit somewhere, not sure where and how to remove it...

**Comment by artem-sedykh** [comment]
HACS is responsible for installing the update and removal if you installed through its store.   
here is my path with files.   
![image](https://user-images.githubusercontent.com/861063/84630410-90094000-aef4-11ea-8fc5-2f754c74bce5.png)

**Comment by tborychowski** [comment]
Thanks!
It looks like it TBH, because when I uninstall a front-end plugin (with hacs) - some plugin shows problems...
Thanks!
