### ISSUE TITLE
Show indicator card on click

### ISSUE THREAD

**Issue by ilarrain** [artem-sedykh/mini-climate-card#5]
Hi, thanks for your custom card!

My request is: Clicking on an indicator should show that indicator's card (e.g. history graph for a sensor entity, as implemented in [custom:simple-thermostat](https://github.com/nervetattoo/simple-thermostat)).
![Captura de pantalla de 2020-06-05 11-55-56](https://user-images.githubusercontent.com/775978/83897598-c8a26000-a723-11ea-81b2-5f88370a4e13.png)

**Comment by artem-sedykh** [comment]
Hello! Cool idea! will do it
