### ISSUE TITLE
Add ability to swap target and actual temperature

### ISSUE THREAD

**Issue by cascer1** [artem-sedykh/mini-climate-card#51]
Hi!

I'd like to be able to swap the target and actual temperature, so the actual temperature is on the left. The current display is very confusing to me because `18 / 20` reads to me like `18 out of requested 20` but in reality it means `18 requested but it is 20`.

**Comment by SaSa1983** [comment]
Hi,

I'd also like to see this implemented.
I feel the same way as @cascer1

**Comment by regevbr** [comment]
released in [2.1.0](https://github.com/artem-sedykh/mini-climate-card/releases/tag/v2.1.0)
