### ISSUE TITLE
Icons for temperature up/down and On/Off gone missing with latest HA update (2021.11.0)

### ISSUE THREAD

**Issue by AdmiralStipe** [artem-sedykh/mini-climate-card#54]
With the latest HA update (2021.11.0) icons for turning A/C on and off and setting the temperature up and down are missing. 

![test](https://user-images.githubusercontent.com/64564398/140330531-3f96181f-50de-4135-b84f-4c184ddf7362.png)

**Comment by chriskob** [comment]
Having the same issue here.

**Comment by Bill-Dung** [comment]
I have the same issue. The buutons are still there but invisible. If you click on them a grey circle appears. The bigger problem is that the Tuya Thermostat does not react when you put the temperature up. Heating is not working at all anymore.

**Comment by ranrinc** [comment]
same experience at my end too

**Comment by oradsa** [comment]
The actions buttons on the bottom are not visible too
![image](https://user-images.githubusercontent.com/4929835/140533423-5352fcf8-f35d-4f8e-b9a7-1f1df640d558.png)

**Comment by treb33** [comment]
Same here
![50618DDB-AD32-461C-B659-A6ACBEC6C32A](https://user-images.githubusercontent.com/18684337/140617647-2bf96526-1e9e-457f-ace0-acd86f0f44c2.jpeg)

**Comment by robfigliooxh** [comment]
SAME :( HELP PLS

**Comment by anhnvme** [comment]
same here. bump this to developer

**Comment by AdmiralStipe** [comment]
A temporary solution, provided by @regevbr available [here](https://gist.github.com/regevbr/bdf7c75599ad53fe3cdd62d1245801b9).

**Comment by ranrinc** [comment]
> A temporary solution, provided by @regevbr available [here](https://gist.github.com/regevbr/bdf7c75599ad53fe3cdd62d1245801b9).

Confirm that this is working great

**Comment by AdmiralStipe** [comment]
Solved with #53
