### ISSUE TITLE
Ability to place fan_mode button near hvac_mode button

### ISSUE THREAD

**Issue by divanikus** [artem-sedykh/mini-climate-card#8]
It would be nice to have an option to place fan mode button onto the main view, so you won't need to toggle to change fan mode. As far as it is just an icon, I believe it shouldn't take much space and will result in a cleaner UI experience.

**Comment by artem-sedykh** [comment]
Hello! It would be nice if you provided 2 layouts with button layout.
1. Layout for desktop
2. Layout for a mobile device (this can be done by pressing F12)
here is an example:
![image](https://user-images.githubusercontent.com/861063/83976065-4753f480-a900-11ea-9dc8-40d870d659e0.png)

**Comment by divanikus** [comment]
It's not that bad on my devices though:
![1](https://user-images.githubusercontent.com/3438036/84047236-ba6a7300-a9b3-11ea-9ae0-83ee90952de2.jpg)
I believe that moving fan icon to the hvac icon wouldn't hurt much. 
![2](https://user-images.githubusercontent.com/3438036/84047241-bb030980-a9b3-11ea-90c6-2dfdc492864b.jpg)

As for your example, fan icon with Слабый label could be clickable and be used as a menu.
