### ISSUE TITLE
New secondary_info type

### ISSUE THREAD

**Issue by julienlarivee** [artem-sedykh/mini-climate-card#9]
Hi,
I would have more of a request than a issue.

I am using your card with my baseboard thermostat. Really great by the way!
My thermostat hvac_mode are always on heating event when they are not actually heating.
Therefore there is an attribute called hvac_action wich is showing if the thermostat is currently heating of inactive.

In the regular thermostat card, they are using this attribute and showing it below the desired temperature.

![image](https://user-images.githubusercontent.com/55027006/84094037-d0832e00-a9c9-11ea-930a-b4b895c5fdd6.png)

Is is possible to get this hvac_action as a new type of secondary_info?

Thank you

**Comment by tibortiz** [comment]
It would be great ! The attributes is "havc_action" in the climate used with your mini-climate-card

**Comment by artem-sedykh** [comment]
Added a new type, so far changes in the dev branch, as I finish other features I will release.  
Here is how the configuration will look for your task: ([release_notes](https://github.com/artem-sedykh/mini-climate-card/blob/dev/release_notes/v1.2.1.md)), if there are suggestions for improvement, write me
